# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for InfluxDB MCP Server updated for Bun
FROM oven/bun:latest

WORKDIR /app

# Install dependencies
COPY package.json bun.lockb ./
RUN bun install --production

# Copy source code
COPY src ./src

# Entrypoint for MCP server (using stdio transport)
ENTRYPOINT ["bun", "src/index.ts"]
